"""quiz_questions.imported_from_question_id (bank import lineage)

Revision ID: 0016_quiz_q_imported_from
Revises: 0015_document_chunks_content_tsv
Create Date: 2026-05-21 16:00:00.000000

Adds a self-referential FK column so a question imported from the
question bank can be traced back to its source. NULL when the question
was authored in-place or generated by the AI pipeline.

Why SET NULL on delete?
  Deleting the source question must not orphan the cloned row — the
  imported question is already a fully detached copy with its own
  options, payload, and revisions. Losing the lineage pointer is the
  expected, non-destructive behaviour.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0016_quiz_q_imported_from"
down_revision = "0015_document_chunks_content_tsv"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "quiz_questions",
        sa.Column(
            "imported_from_question_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_quiz_questions_imported_from",
        source_table="quiz_questions",
        referent_table="quiz_questions",
        local_cols=["imported_from_question_id"],
        remote_cols=["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "idx_quiz_questions_imported_from",
        "quiz_questions",
        ["imported_from_question_id"],
        postgresql_where=sa.text("imported_from_question_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "idx_quiz_questions_imported_from",
        table_name="quiz_questions",
    )
    op.drop_constraint(
        "fk_quiz_questions_imported_from",
        "quiz_questions",
        type_="foreignkey",
    )
    op.drop_column("quiz_questions", "imported_from_question_id")
