"""Add material_processing + quiz_generation notification categories.

Revision ID: 0040_notif_job_cats
Revises: 0039_lesson_discuss
Create Date: 2026-07-24 00:00:00.000000

Teachers who kick off an async material-ingestion or quiz-generation job get
no signal when it finishes. This widens the notification taxonomy so the two
worker pipelines can dispatch a completion (or failure) notification through
the existing ``send_notification`` surface.

Two BROAD categories are added (each covers both success and failure so a
teacher has one preference toggle per job type):

* ``material_processing``  — material ingestion finished / failed
* ``quiz_generation``      — quiz AI generation finished / failed

Both CHECK constraints are widened:

* ``notifications_category_check``            (the inbox rows)
* ``notification_preferences_category_check`` (the per-user email toggles)

The constraints are dropped and recreated with the extended value set. No data
migration is needed — existing rows use the legacy categories which remain
valid. Downgrade recreates the original constraints; it will FAIL if any row
already uses a new category (expected — you must clear those first).
"""

from __future__ import annotations

from alembic import op

# NOTE: alembic_version.version_num is varchar(32); keep this id <= 32 chars.
revision = "0040_notif_job_cats"
down_revision = "0039_lesson_discuss"
branch_labels = None
depends_on = None


# Real DB constraint names (auto-generated by the baseline migration, NOT the
# ORM ``ck_*`` names — verified against the live schema before writing this).
_NOTIF_CONSTRAINT = "notifications_category_check"
_PREF_CONSTRAINT = "notification_preferences_category_check"

# --- notifications.category ---------------------------------------------------
_NOTIF_OLD = (
    "spaced_repetition",
    "lesson_unlock",
    "interview_result",
    "course_announcement",
    "system",
)
_NOTIF_NEW = (*_NOTIF_OLD, "material_processing", "quiz_generation")

# --- notification_preferences.category ---------------------------------------
_PREF_OLD = (
    "course_updates",
    "ai_recommendations",
    "spaced_repetition",
    "lesson_unlock",
    "interview_result",
    "course_announcement",
    "system",
)
_PREF_NEW = (*_PREF_OLD, "material_processing", "quiz_generation")


def _in_list(values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{v}'" for v in values)
    return f"category IN ({joined})"


def upgrade() -> None:
    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(
        _NOTIF_CONSTRAINT, "notifications", _in_list(_NOTIF_NEW)
    )

    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _in_list(_PREF_NEW)
    )


def _in_values(values: tuple[str, ...]) -> str:
    quoted = ", ".join("'" + v + "'" for v in values)
    return "(" + quoted + ")"


def downgrade() -> None:
    # Rows carrying the categories this migration introduced would violate
    # the narrower constraint being restored, aborting the whole downgrade.
    # They cannot exist below this revision, so removing them IS the
    # downgrade.
    op.execute(
        "DELETE FROM notifications WHERE category NOT IN " + _in_values(_NOTIF_OLD)
    )
    op.execute(
        "DELETE FROM notification_preferences WHERE category NOT IN "
        + _in_values(_PREF_OLD)
    )
    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(
        _NOTIF_CONSTRAINT, "notifications", _in_list(_NOTIF_OLD)
    )

    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _in_list(_PREF_OLD)
    )
