"""Add interview_generation notification category.

Revision ID: 0058_interview_gen_notif
Revises: 0057_quiz_audit_events
Create Date: 2026-07-25 00:00:00.000000

Teachers who kick off async interview-question generation get no signal when it
finishes — mirroring the gap quiz generation had before ``0040``. This widens
the notification taxonomy so the interview generation pipeline can dispatch a
completion (or failure) notification through the existing ``send_notification``
surface.

One BROAD category is added (covers both success and failure so a teacher has a
single preference toggle for the job type):

* ``interview_generation`` — interview AI question generation finished / failed

Both CHECK constraints are widened:

* ``notifications_category_check``            (the inbox rows)
* ``notification_preferences_category_check`` (the per-user email toggles)

The constraints are dropped and recreated with the extended value set. No data
migration is needed — existing rows use the prior categories which remain
valid. Downgrade recreates the previous constraints; it will FAIL if any row
already uses the new category (expected — clear those first).
"""

from __future__ import annotations

from alembic import op

# NOTE: alembic_version.version_num is varchar(32); keep this id <= 32 chars.
revision = "0058_interview_gen_notif"
down_revision = "0057_quiz_audit_events"
branch_labels = None
depends_on = None


# Real DB constraint names (auto-generated by the baseline migration, NOT the
# ORM ``ck_*`` names — mirrors 0040 which widened these same constraints).
_NOTIF_CONSTRAINT = "notifications_category_check"
_PREF_CONSTRAINT = "notification_preferences_category_check"

# --- notifications.category ---------------------------------------------------
_NOTIF_OLD = (
    "spaced_repetition",
    "lesson_unlock",
    "interview_result",
    "course_announcement",
    "system",
    "material_processing",
    "quiz_generation",
)
_NOTIF_NEW = (*_NOTIF_OLD, "interview_generation")

# --- notification_preferences.category ---------------------------------------
_PREF_OLD = (
    "course_updates",
    "ai_recommendations",
    "spaced_repetition",
    "lesson_unlock",
    "interview_result",
    "course_announcement",
    "system",
    "material_processing",
    "quiz_generation",
)
_PREF_NEW = (*_PREF_OLD, "interview_generation")


def _in_list(values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{v}'" for v in values)
    return f"category IN ({joined})"


def upgrade() -> None:
    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(
        _NOTIF_CONSTRAINT, "notifications", _in_list(_NOTIF_NEW)
    )

    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _in_list(_PREF_NEW)
    )


def _in_values(values: tuple[str, ...]) -> str:
    quoted = ", ".join("'" + v + "'" for v in values)
    return "(" + quoted + ")"


def downgrade() -> None:
    # Rows carrying the categories this migration introduced would violate
    # the narrower constraint being restored, aborting the whole downgrade.
    # They cannot exist below this revision, so removing them IS the
    # downgrade.
    op.execute(
        "DELETE FROM notifications WHERE category NOT IN " + _in_values(_NOTIF_OLD)
    )
    op.execute(
        "DELETE FROM notification_preferences WHERE category NOT IN "
        + _in_values(_PREF_OLD)
    )
    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(
        _NOTIF_CONSTRAINT, "notifications", _in_list(_NOTIF_OLD)
    )

    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _in_list(_PREF_OLD)
    )
