"""Path-change review: ``in_progress`` status + structured rejection reason.

Revision ID: 0097_path_change_in_progress
Revises: 0096_drop_iq_bank_tags
Create Date: 2026-09-01 00:00:00.000000

A Faculty Dean had exactly two moves on a path-change request — approve or
reject — and both are terminal. A student who filed a request saw "Waiting for
Faculty Dean review" from submission until the decision landed, with no way to
tell an untouched request from one actively being checked, and the dean had no
way to park a request they had opened but not finished verifying.

This revision adds the missing middle state and gives rejection a machine
reason:

* ``status`` gains ``in_progress`` — the dean has seen the request and is
  checking the student's data. Not terminal: the request is still *open*.
* ``in_progress_at`` / ``in_progress_by`` record who acknowledged it and when,
  so the dashboard can age the queue by "unseen" vs "being handled" instead of
  one undifferentiated pending pile.
* ``decision_reason_code`` carries a fixed vocabulary for rejections so the
  reason is filterable/reportable, while the existing free-text
  ``decision_reason`` keeps the dean's own words (mandatory for ``other``).

**The partial unique index is the load-bearing part.** It previously enforced
one request per enrolment ``WHERE status = 'pending'``. Left alone, flipping a
request to ``in_progress`` would vacate that slot and let the student file a
second request while the dean is mid-review — two open requests for one
enrolment, which every downstream guard (``get_pending_request``, the switch
budget recheck) assumes cannot happen. The index is therefore rebuilt over both
OPEN statuses and renamed ``uq_path_change_requests_one_open`` so the name
states the invariant.

The notification taxonomy also gains ``path_change_review`` so the student can
be told when their request is picked up / decided, on the same
preference-gated channel as every other notification.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# NOTE: alembic_version.version_num is varchar(32); keep this id <= 32 chars.
revision = "0097_path_change_in_progress"
down_revision = "0096_drop_iq_bank_tags"
branch_labels = None
depends_on = None


_STATUS_CONSTRAINT = "ck_path_change_requests_status"
_STATUS_OLD = ("pending", "approved", "rejected", "cancelled", "invalidated")
_STATUS_NEW = ("pending", "in_progress", "approved", "rejected", "cancelled", "invalidated")

_OLD_INDEX = "uq_path_change_requests_one_pending"
_NEW_INDEX = "uq_path_change_requests_one_open"

_REASON_CODE_CONSTRAINT = "ck_path_change_requests_decision_reason_code"
# Kept in sync with ``learning_programs.models.PATH_CHANGE_REJECTION_REASON_CODES``.
_REASON_CODES = (
    "insufficient_justification",
    "progress_loss_too_high",
    "target_path_not_suitable",
    "preserve_remaining_switch",
    "advising_required",
    "documentation_missing",
    "other",
)

# Real DB constraint names (auto-generated by the baseline migration, NOT the
# ORM ``ck_*`` names) — same pair 0040 / 0058 widened.
_NOTIF_CONSTRAINT = "notifications_category_check"
_PREF_CONSTRAINT = "notification_preferences_category_check"

_NOTIF_OLD = (
    "spaced_repetition",
    "lesson_unlock",
    "interview_result",
    "course_announcement",
    "system",
    "material_processing",
    "quiz_generation",
    "interview_generation",
)
_NOTIF_NEW = (*_NOTIF_OLD, "path_change_review")

_PREF_OLD = ("course_updates", "ai_recommendations", *_NOTIF_OLD)
_PREF_NEW = (*_PREF_OLD, "path_change_review")


def _status_in(values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{v}'" for v in values)
    return f"status IN ({joined})"


def _category_in(values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{v}'" for v in values)
    return f"category IN ({joined})"


def _in_values(values: tuple[str, ...]) -> str:
    return "(" + ", ".join(f"'{v}'" for v in values) + ")"


def upgrade() -> None:
    op.drop_constraint(_STATUS_CONSTRAINT, "path_change_requests", type_="check")
    op.create_check_constraint(
        _STATUS_CONSTRAINT, "path_change_requests", _status_in(_STATUS_NEW)
    )

    op.add_column(
        "path_change_requests",
        sa.Column("in_progress_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "path_change_requests",
        sa.Column(
            "in_progress_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="NO ACTION"),
            nullable=True,
        ),
    )
    op.add_column(
        "path_change_requests",
        sa.Column("decision_reason_code", sa.String(40), nullable=True),
    )
    op.create_check_constraint(
        _REASON_CODE_CONSTRAINT,
        "path_change_requests",
        "decision_reason_code IS NULL OR decision_reason_code IN " + _in_values(_REASON_CODES),
    )

    # One OPEN request per enrolment: pending *and* in_progress both occupy the
    # slot, so acknowledging a request cannot let a second one in behind it.
    op.drop_index(_OLD_INDEX, table_name="path_change_requests")
    op.create_index(
        _NEW_INDEX,
        "path_change_requests",
        ["program_enrollment_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'in_progress')"),
    )

    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(_NOTIF_CONSTRAINT, "notifications", _category_in(_NOTIF_NEW))
    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _category_in(_PREF_NEW)
    )


def downgrade() -> None:
    # An in_progress request is an OPEN request; below this revision the only
    # open status is 'pending', so demoting is the faithful inverse (the
    # acknowledgement columns are dropped with it).
    op.execute("UPDATE path_change_requests SET status = 'pending' WHERE status = 'in_progress'")

    op.drop_index(_NEW_INDEX, table_name="path_change_requests")
    op.create_index(
        _OLD_INDEX,
        "path_change_requests",
        ["program_enrollment_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )

    op.drop_constraint(_REASON_CODE_CONSTRAINT, "path_change_requests", type_="check")
    op.drop_column("path_change_requests", "decision_reason_code")
    op.drop_column("path_change_requests", "in_progress_by")
    op.drop_column("path_change_requests", "in_progress_at")

    op.drop_constraint(_STATUS_CONSTRAINT, "path_change_requests", type_="check")
    op.create_check_constraint(
        _STATUS_CONSTRAINT, "path_change_requests", _status_in(_STATUS_OLD)
    )

    # Rows carrying the category this migration introduced would violate the
    # narrower constraint being restored, aborting the whole downgrade.
    op.execute("DELETE FROM notifications WHERE category NOT IN " + _in_values(_NOTIF_OLD))
    op.execute(
        "DELETE FROM notification_preferences WHERE category NOT IN " + _in_values(_PREF_OLD)
    )
    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(_NOTIF_CONSTRAINT, "notifications", _category_in(_NOTIF_OLD))
    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _category_in(_PREF_OLD)
    )
