"""Add the ``course_discussion`` notification category.

Discussion comments on lessons (student -> teacher, teacher -> student)
need their own notification category so a user's preference toggle for
"course discussion activity" is separate from course announcements.

Revision ID: 0101_discussion_notify_category
Revises: 0100_quiz_question_bank
"""

from __future__ import annotations

from alembic import op

revision = "0101_discussion_notify_category"
down_revision = "0100_quiz_question_bank"
branch_labels = None
depends_on = None

# Real DB constraint names (auto-generated by the baseline migration, NOT the
# ORM ``ck_*`` names) — same pair 0040 / 0058 / 0097 widened.
_NOTIF_CONSTRAINT = "notifications_category_check"
_PREF_CONSTRAINT = "notification_preferences_category_check"

_NOTIF_OLD = (
    "spaced_repetition",
    "lesson_unlock",
    "interview_result",
    "course_announcement",
    "system",
    "material_processing",
    "quiz_generation",
    "interview_generation",
    "path_change_review",
)
_NOTIF_NEW = (*_NOTIF_OLD, "course_discussion")

_PREF_OLD = ("course_updates", "ai_recommendations", *_NOTIF_OLD)
_PREF_NEW = (*_PREF_OLD, "course_discussion")


def _category_in(values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{v}'" for v in values)
    return f"category IN ({joined})"


def upgrade() -> None:
    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(_NOTIF_CONSTRAINT, "notifications", _category_in(_NOTIF_NEW))
    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _category_in(_PREF_NEW)
    )


def downgrade() -> None:
    # Rows carrying the category this migration introduced would violate the
    # narrower constraint being restored, aborting the whole downgrade.
    # They cannot exist below this revision, so removing them IS the downgrade.
    op.execute(
        "DELETE FROM notifications WHERE category NOT IN "
        "('spaced_repetition', 'lesson_unlock', 'interview_result', "
        "'course_announcement', 'system', 'material_processing', "
        "'quiz_generation', 'interview_generation', 'path_change_review')"
    )
    op.execute(
        "DELETE FROM notification_preferences WHERE category NOT IN "
        "('course_updates', 'ai_recommendations', 'spaced_repetition', "
        "'lesson_unlock', 'interview_result', 'course_announcement', 'system', "
        "'material_processing', 'quiz_generation', 'interview_generation', "
        "'path_change_review')"
    )
    op.drop_constraint(_NOTIF_CONSTRAINT, "notifications", type_="check")
    op.create_check_constraint(_NOTIF_CONSTRAINT, "notifications", _category_in(_NOTIF_OLD))
    op.drop_constraint(_PREF_CONSTRAINT, "notification_preferences", type_="check")
    op.create_check_constraint(
        _PREF_CONSTRAINT, "notification_preferences", _category_in(_PREF_OLD)
    )
