"""Generate the LaTeX API tables from the live OpenAPI schema.

Chapter 5 and Appendix API-Design both state how large the API surface is. Both
were typed by hand, both drifted, and the chapter still claimed "195 routes
across 12 features" long after the surface had roughly doubled. A number that is
retyped every release is a number that goes stale between releases.

This script is the fix: it asks the application for its own schema and emits the
tables. Run it whenever the surface changes and paste (or ``\\input``) the
result. If the table is generated it cannot contradict the code.

Usage
-----

    uv run python scripts/gen_api_tables.py --out ../co4029_latex/generated

Writes two files:

``api_surface_by_prefix.tex``
    The summary table for Section 5.3 --- operation counts per top-level path
    prefix, which is what the chapter needs and all it needs.

``api_operations_by_feature.tex``
    The per-operation catalogue for the appendix, grouped by feature package,
    with method, path and summary.

Both are fragments: no preamble, no document environment, so they ``\\input``
straight into the existing chapter and appendix.
"""

from __future__ import annotations

import argparse
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

#: Order the summary table is presented in. Anything not listed is appended
#: alphabetically, so a new prefix shows up rather than being silently dropped.
_PREFIX_ORDER = (
    "/teacher",
    "/admin",
    "/management",
    "/me",
    "/dept",
    "/users",
    "/courses",
    "/auth",
    "/interview-sessions",
    "/discussion",
    "/attempts",
    "/materials",
    "/lessons",
    "/modules",
    "/career-paths",
    "/policies",
    "/quizzes",
    "/interview-configs",
    "/lesson-resources",
)

_API_PREFIX = "/api/v1"


def _escape(text: str) -> str:
    """LaTeX-escape a summary string.

    Summaries come from function names and docstrings, so they contain
    underscores and ampersands often enough that not escaping them would break
    the build on the next unlucky endpoint.
    """
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _prefix_of(path: str) -> str:
    """The top-level segment an operation is grouped under."""
    trimmed = path[len(_API_PREFIX) :] if path.startswith(_API_PREFIX) else path
    match = re.match(r"^(/[^/{]+)", trimmed)
    if not match:
        return "health/root"
    return match.group(1)


def _collect(schema: dict[str, Any]) -> tuple[Counter[str], dict[str, list[tuple]]]:
    """``(operations per prefix, operations per feature tag)``."""
    per_prefix: Counter[str] = Counter()
    per_feature: dict[str, list[tuple]] = defaultdict(list)
    for path, item in schema.get("paths", {}).items():
        for method, operation in item.items():
            if method.upper() not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            per_prefix[_prefix_of(path)] += 1
            tags = operation.get("tags") or ["untagged"]
            per_feature[tags[0]].append(
                (method.upper(), path, operation.get("summary", ""))
            )
    return per_prefix, per_feature


def _summary_table(per_prefix: Counter[str]) -> str:
    ordered = [p for p in _PREFIX_ORDER if p in per_prefix]
    ordered += sorted(set(per_prefix) - set(ordered))
    total = sum(per_prefix.values())

    rows = "\n".join(
        rf"\path|{p}| & {per_prefix[p]} \\ \hline" for p in ordered
    )
    return (
        "% GENERATED by scripts/gen_api_tables.py -- do not edit by hand.\n"
        "\\begin{table}[H]\n\\centering\n"
        "\\renewcommand{\\arraystretch}{1.25}\n\\small\n"
        "\\begin{tabular}{|l|r|}\n\\hline\n"
        "\\textbf{Path prefix} & \\textbf{Operations} \\\\ \\hline\n"
        f"{rows}\n"
        f"\\textbf{{Total}} & \\textbf{{{total}}} \\\\ \\hline\n"
        "\\end{tabular}\n"
        "\\caption{REST operations by top-level path prefix.}\n"
        "\\label{tab:api_surface_by_prefix}\n"
        "\\end{table}\n"
    )


def _catalogue(per_feature: dict[str, list[tuple]]) -> str:
    chunks = [
        "% GENERATED by scripts/gen_api_tables.py -- do not edit by hand.\n"
    ]
    for feature in sorted(per_feature):
        operations = sorted(per_feature[feature], key=lambda row: (row[1], row[0]))
        rows = "\n".join(
            rf"\texttt{{{method}}} & \path|{path}| & {_escape(summary)} \\ \hline"
            for method, path, summary in operations
        )
        chunks.append(
            f"\\subsection{{{_escape(feature.title())}}}\n"
            "\\renewcommand{\\arraystretch}{1.25}\n\\small\n"
            "\\begin{longtable}"
            "{|>{\\raggedright\\arraybackslash}m{0.08\\textwidth}"
            "|>{\\raggedright\\arraybackslash}m{0.44\\textwidth}"
            "|>{\\raggedright\\arraybackslash}m{0.38\\textwidth}|}\n"
            f"\\caption{{{_escape(feature.title())} endpoints.}}\n"
            f"\\label{{tab:api_{re.sub(r'[^a-z0-9]+', '_', feature.lower())}}} \\\\\n"
            "\\hline\n\\textbf{Method} & \\textbf{Path} & \\textbf{Purpose} \\\\ \\hline\n"
            "\\endfirsthead\n"
            "\\multicolumn{3}{c}{{\\bfseries Table \\thetable\\ -- Continued}} \\\\ \\hline\n"
            "\\textbf{Method} & \\textbf{Path} & \\textbf{Purpose} \\\\ \\hline\n"
            "\\endhead\n\\hline\n\\endfoot\n\n"
            f"{rows}\n\n"
            "\\end{longtable}\n\\normalsize\n"
        )
    return "\n".join(chunks)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Directory the .tex fragments are written to.",
    )
    args = parser.parse_args()

    # Imported here, not at module scope: the import pulls in the whole app and
    # this file should stay readable (and --help should work) without it.
    from abridgeai.api import create_app  # noqa: PLC0415

    schema = create_app().openapi()
    per_prefix, per_feature = _collect(schema)

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "api_surface_by_prefix.tex").write_text(
        _summary_table(per_prefix), encoding="utf-8"
    )
    (args.out / "api_operations_by_feature.tex").write_text(
        _catalogue(per_feature), encoding="utf-8"
    )

    total = sum(per_prefix.values())
    print(f"{total} operations across {len(schema.get('paths', {}))} paths")
    print(f"{len(per_feature)} feature tags")
    print(f"wrote {args.out / 'api_surface_by_prefix.tex'}")
    print(f"wrote {args.out / 'api_operations_by_feature.tex'}")


if __name__ == "__main__":
    main()
